package solr

const (
	rawStatus              string = "status"
	rawResponse            string = "response"
	rawFacetsCount         string = "facet_counts"
	rawFacetFields         string = "facet_fields"
	rawNumFound            string = "numFound"
	rawResponseHeader      string = "responseHeader"
	rawQtime               string = "QTime"
	stringBar              string = "/"
	stringSolrBase         string = "solr"
	stringFacet            string = "bjqfacet?"
	stringSelect           string = "select?"
	rawParserStatus        string = "status"
	rawParserCollections   string = "collections"
	contentType            string = "application/json"
	unloadCore             string = "/solr/admin/cores?action=UNLOAD&core="
	deleteInstanceTrue     string = "&deleteInstanceDir=true"
	actionStatus           string = "/solr/admin/cores?action=STATUS&wt=json"
	actionCreateCore       string = "/solr/admin/cores?action=CREATE&name="
	instanceDir            string = "&instanceDir="
	config                 string = "&config="
	schema                 string = "&schema="
	dataDir                string = "&dataDir="
	actionCreateCollection string = "/solr/admin/collections?action=CREATE&name="
	collectionConfigName   string = "&collection.configName="
	maxShardsPerNode       string = "&maxShardsPerNode="
	numShards              string = "&numShards="
	replicationFactor      string = "&replicationFactor="
	deleteCollection       string = "/solr/admin/collections?action=DELETE&name="
	listCollection         string = "/solr/admin/collections?action=LIST&indexInfo=false&wt=json"
	wtJSON                 string = "&wt=json"
	stringSort             string = "&sort="
	stringQ                string = "&q="
	stringFL               string = "&fl="
	stringFQ               string = "&fq="
	stringFacetTrue        string = "&facet=true&"
	stringEqual            string = "="
	stringStart            string = "&start="
	stringRows             string = "&rows="
	stringUpdate           string = "/update?"
	stringAmpersand        string = "&"
	stringCommitTrue       string = "commit=true"
)
